spring:
  application:
    name: control-finanzas-server
  datasource:
    url: jdbc:postgresql://localhost:5432/finanzas
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management.endpoints.web.exposure.include: health,info

springdoc:
  api-docs:
    path: /api/v1/openapi
  swagger-ui:
    path: /swagger-ui
    urlsPrimaryName: default
